spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/connectdb
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false #hibernate 5의 AUTO의 전략이 TABLE
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: local


  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  messages:
    basename: messages,errors
  data:
    web:
      pageable:
        max-page-size: 100

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


server:
  error:
    include-message: always
  port: 8080


#swagger springdoc-ui 설정
springdoc:
  packages-to-scan: study.board
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
  #    path:
  api-docs:
    path: /api-docs/board  #openAPI 접근 경로
#    groups:
#      enabled: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

# AWS S3 설정
cloud:
  aws:
    credentials:
      access-key: AKIAVEHKD22V4D7J5S5S
      secret-key: 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
    s3:
      bucket: cjyfirstbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false


